# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_stud_faculty_status_faculty_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cc_process_trigger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='dept_process_trigger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='gymkhana_process_trigger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='hostel_process_trigger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='library_process_trigger',
            field=models.BooleanField(default=False),
        ),
    ]
