# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170308_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lab_process_trigger',
            field=models.BooleanField(default=False),
        ),
    ]
