# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_student_lab_process_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account_remarks',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='assistant_registrar_remarks',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='caretaker_remarks',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='cc_remarks',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='gymkhana_remarks',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='library_remarks',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='online_cc_remarks',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='submit_thesis_remarks',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='warden_remarks',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
