# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170309_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hod_remarks',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
